### ISSUE TITLE
Web Sayfa Tasarımı Ortak Ayrıntılar

### ISSUE THREAD

**Issue by suleymangunes** [suleymangunes/BilgiPaylasimPlatformu#7]
Web sayfalarında ortak kullanılacak yazi tipi, sayfa duzeninde kullanılacak oranlar belirlenecek.

**Comment by hamzaeroglu** [comment]
Taslaklardan yola çıkarak sayfa düzeninde kullanılacak oranlar belirlendi. Değişikliğe açık olmakla beraber olabildiğince bu oranlara sadık kalınmalıdır.
